### ISSUE TITLE
Favourited tags look odd on Gaming StackExchange

### ISSUE THREAD

**Issue by SeinopSys** [soscripted/sox#29]
**Installed Version: 1.0.2 |  Environment: Chrome/Tampermonkey**

**Expected Behaviour**

The tag is properly coloured & outlined:
![](http://i.imgur.com/bblmOth.png)

This is can be achieved using:
```css
a.post-tag {
    border-color: rgba(0,0,0,.3);
    background-color: rgb(195, 218, 250);
}
a.post-tag:before {
    border-color: inherit;
    background-color: inherit;
}
```

**Actual Behaviour**

Only the main block part of the tag is coloured and the border is dropped:
**![](http://i.imgur.com/GBZQoPG.png)**

This is done by the following CSS:
```css
element.style {
    border-width: 0px;
    background-color: rgb(195, 218, 250);
}
```

**Error Logs**: N/A

**Steps to reproduce**

Enable "Highlight only the favourite tags for favourite questions" and visit http://gaming.stackexchange.com/ while having some favourite tags.
